server:
    name: "async-email-mq-service"
    host: "0.0.0.0"
    port: 1010
postgre:
    primary:
        connString: "postgres://postgres:postgres@127.0.0.1:54320/database?sslmode=disable"        
        maxOpenConn: 350
        maxIdleConn: 10
        maxConnLifeTimeInSecond: 10
rabbitmq:
    primary:
        connString: "amqp://guest:guest@127.0.0.1:5672"