server:
    name: "project-mq-service"
    host: "0.0.0.0"
    port: 1010
postgre:
    primary:
        connString: "postgres://postgres:postgres@project-mq-pg-14:5432/database?sslmode=disable"
        maxOpenConn: 350
        maxIdleConn: 10
        maxConnLifeTimeInSecond: 10
mq:
    connString: "amqp://guest:guest@project-mq-rabbitmq:5672/"